/** @type {import('tailwindcss').Config} */

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: ["theme--dark", "theme--light"],
  theme: {
    screens: {
      sm: { max: "600px" },
      md: { min: "601px", max: "1279px" },
      lg: { min: "1280px" },
    },
    fontSize: {
      "4xs": "var(--text-size-xxxxs)",
      "3xs": "var(--text-size-xxxs)",
      "2xs": "var(--text-size-xxs)",
      xs: "var(--text-size-xs)",
      base: "var(--text-size-s)",
      xsm: "var(--text-size-xsm)",
      sm: "var(--text-size-sm)",
      md: "var(--text-size-md)",
      lg: "var(--text-size-lg)",
      xl: "var(--text-size-xl)",
      "2xl": "var(--text-size-2xl)",
    },
    lineHeight: {
      xs: "var(--text-lh-xxs)",
      sm: "var(--text-lh-xs)",
      base: "var(--text-lh-s)",
      md: "var(--text-lh-m)",
      lg: "var(--text-lh-l)",
      xl: "var(--text-lh-xl)",
      "2xl": "var(--text-lh-2xl)",
    },
    textColor: {
      prominent: "var(--text-prominent)",
      general: "var(--text-general)",
      disabled: "var(--text-disabled)",
      red: "var(--text-red)",
      "colored-background": "var(--text-colored-background)",
      "info-blue": "var(--text-info-blue)",
      "info-blue-background": "var(--text-info-blue-background)",
      "status-info-blue": "var(--text-status-info-blue)",
      "text-hint": "var(--text-hint)",
      "disabled-1": "var(--text-disabled-1)",
      "profit-success": "var(--text-profit-success)",
      "loss-danger": "var(--text-loss-danger)",
    },
    borderColor: {
      default: "var(--border-normal)",
      "normal-1": "var(--border-normal-1)",
      "normal-2": "var(--border-normal-2)",
      "normal-3": "var(--border-normal-3)",
      hover: "var(--border-hover)",
      "hover-1": "var(--border-hover-1)",
      active: "var(--border-active)",
      disabled: "var(--border-disabled)",
      divider: "var(--border-divider)",
    },
    colors: {
      brand: {
        white: "var(--brand-white)",
        "dark-grey": "var(--brand-dark-grey)",
        "red-coral": "var(--brand-red-coral)",
        orange: "var(--brand-orange)",
        secondary: "var(--brand-secondary)",
      },
      general: {
        "main-1": "var(--general-main-1)",
        "main-2": "var(--general-main-2)",
        "main-3": "var(--general-main-3)",
        "main-4": "var(--general-main-4)",
        "section-1": "var(--general-section-1)",
        "section-2": "var(--general-section-2)",
        "section-3": "var(--general-section-3)",
        "section-4": "var(--general-section-4)",
        "section-5": "var(--general-section-5)",
        "section-6": "var(--general-section-6)",
        disabled: "var(--general-disabled)",
        hover: "var(--general-hover)",
      },
      icon: {
        light: "var(--icon-light-background)",
        dark: "var(--icon-dark-background)",
        grey: "var(--icon-grey-background)",
      },
      status: {
        default: "var(--status-default)",
        adjustment: "var(--status-adjustment)",
        danger: "var(--status-danger)",
        info: "var(--status-info)",
        warning: "var(--status-warning)",
        success: "var(--status-success)",
        transfer: "var(--status-transfer)",
        "warning-transparent": "var(--status-warning-transparent)",
        "colored-background": "var(--status-colored-background)",
        "alert-background": "var(--status-alert-background)",
      },
      badge: {
        white: "var(--badge-white)",
        blue: "var(--badge-blue)",
        green: "var(--badge-green)",
        violet: "var(--badge-violet)",
      },
      base: {
        white: "#ffffff",
        black: {
          100: "#5c5c5c",
          200: "#3e3e3e",
          300: "#323738",
          400: "#333333",
          500: "#242828",
          600: "#1d1f20",
          700: "#151717",
          800: "#0e0e0e",
          900: "#000000",
        },
        blue: {
          100: "#e0fcff",
          200: "#bbe1fa",
          300: "#3292ff",
          400: "#377cfc",
          500: "#2274a5",
          600: "#2bcbba",
          700: "#4ea8de",
          800: "#4e89ae",
          900: "#3d3f4d",
          1000: "#1a1c2c",
        },
        brown: "#664407",
        green: {
          100: "#4bb4b329",
          200: "#e8fdf8",
          300: "#17eabd",
          400: "#cedddf",
          500: "#85acb0",
          600: "#4bb4b3",
          700: "#00a79e",
          800: "#3d9494",
          900: "#008079",
        },
        gray: {
          100: "#fafafa",
          200: "#f5f7fa",
          300: "#f2f3f4",
          400: "#eaeced",
          500: "#e6e9e9",
          600: "#d6dadb",
          700: "#d7d7d7",
          800: "#d6d6d6",
          900: "#c2c2c2",
          1000: "#919191",
          1100: "#868686",
          1200: "#999999",
          1300: "#6e6e6e",
          1400: "#2e2e2e",
        },
        red: {
          100: "#fce3e3",
          200: "#ffe1e3",
          300: "#ff444f",
          400: "#ec3f3f",
          500: "#eb3e48",
          600: "#d33636",
          700: "#b33037",
          800: "#cc2e3d",
          900: "#a32430",
          1000: "#661b20",
        },
        yellow: {
          100: "#ffad3a",
          200: "#ffa912",
          300: "#b3760d",
          400: "rgba(255, 173, 58, 0.16)",
        },
      },
    },
  },
};
